client.secret=111dgda0v39fabshcrt9sq8553gm9kb59kp1s53cabqpv2s80vlu
client.id=1uugf4u95d675duna736pojgt0
oauthURL=https://us-east-2o9bhtzyth.auth.us-east-2.amazoncognito.com/oauth2/token
loginURL=https://us-east-2o9bhtzyth.auth.us-east-2.amazoncognito.com/login
redirectURL=http://localhost:8080/harvestmadison_war/auth
region=us-east-2
poolId=us-east-2_O9bhTZytH