driver=com.mysql.cj.jdbc.Driver
url=url=jdbc:mysql://awseb-e-bvqmpptg22-stack-awsebrdsdatabase-5rjwqge3sxll.c52oagosm6pr.us-east-2.rds.amazonaws.com:3306/harvest_madison
username=harvest_madison
password=madison